# Generated by Django 4.0.4 on 2022-05-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_privatechatroom_id_alter_roomchatmessage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomchatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unreadchatroommessages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unreadchatroommessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
