# Generated by Django 4.0.4 on 2022-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_privatechatroom_id_alter_roomchatmessage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadchatroommessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
