# Generated by Django 4.0.4 on 2022-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_unreadchatroommessages_most_recent_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadchatroommessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
